name: Windows run Linux container

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify Docker version
        run: docker version

      - name: Run a Linux container
        run: |
          docker run --rm ubuntu:22.04 bash -c "echo Hello from Linux container! && uname -a"